self-hosted-runner:
  labels: []
config-variables:
  - APP_ID
  - GOOGLE_CLOUD_LOCATION
  - GOOGLE_CLOUD_PROJECT
  - SERVICE_ACCOUNT_EMAIL
  - GCP_WIF_PROVIDER
  - DEBUG
  - ACTIONS_STEP_DEBUG
  - GEMINI_MODEL
  - GOOGLE_GENAI_USE_GCA
  - GOOGLE_GENAI_USE_VERTEXAI
  - UPLOAD_ARTIFACTS
