images:
  - us-central1-docker.pkg.dev/$PROJECT_ID/nexus-repo/frontend:$COMMIT_SHA
steps:
  # 1. Build da Imagem Docker SOTA
  - args:
      - build
      - '-t'
      - us-central1-docker.pkg.dev/$PROJECT_ID/nexus-repo/frontend:$COMMIT_SHA
      - '-t'
      - us-central1-docker.pkg.dev/$PROJECT_ID/nexus-repo/frontend:latest
      - '-f'
      - frontend/Dockerfile
      - ./frontend
    name: gcr.io/cloud-builders/docker

  # 2. Push para o Artifact Registry
  - args:
      - push
      - us-central1-docker.pkg.dev/$PROJECT_ID/nexus-repo/frontend
      - '--all-tags'
    name: gcr.io/cloud-builders/docker

  # 3. Deploy Serverless no Cloud Run (Auto-Scaling de 0 a N)
  - args:
      - run
      - deploy
      - nexus-frontend
      - '--image'
      - us-central1-docker.pkg.dev/$PROJECT_ID/nexus-repo/frontend:$COMMIT_SHA
      - '--region'
      - us-central1
      - '--allow-unauthenticated'
      - '--port'
      - '3000'
    entrypoint: gcloud
    name: gcr.io/google.com/cloudsdktool/cloud-sdk