#!/usr/bin/env python3
"""Google Jules Model Context Protocol (MCP) Server.

Fornece interface padrao MCP sobre STDIO para orquestracao de sessoes em VMs isoladas do Google Jules.
Conformidade: Protocolo Chico SOTA v8.0 GOLD (Python 3.12+, Zero-Any, Logging stderr-only).
"""
from __future__ import annotations

import json
import logging
import sys

# Configuracao de Logging estritamente para stderr para nao corromper o fluxo JSON-RPC no stdout
logging.basicConfig(
    level=logging.INFO,
    stream=sys.stderr,
    format="[JULES MCP] %(asctime)s - %(levelname)s - %(message)s",
)
logger = logging.getLogger("jules_mcp_server")

try:
    from mcp.server.mcpserver import MCPServer
except ImportError:
    try:
        from mcp.server.fastmcp import FastMCP as MCPServer  # type: ignore[no-redef]
    except ImportError:
        logger.critical("mcp SDK nao encontrado no ambiente.")
        sys.exit(1)

# Importa a engine de conexao canônica do Jules
try:
    from engine.jules_bridge import JulesClient, JulesSessionRequest
except ImportError:
    from pathlib import Path
    current_dir = Path(__file__).resolve().parent
    sys.path.insert(0, str(current_dir.parent))
    from engine.jules_bridge import JulesClient, JulesSessionRequest


server = MCPServer("google-jules")
client = JulesClient()


@server.tool(
    name="jules_create_session",
    description="Creates and starts an asynchronous cloud coding session in an isolated Google Jules VM.",
)
def jules_create_session(
    source: str,
    prompt: str,
    branch: str = "main",
    auto_approve_plan: bool = False,
) -> str:
    """Cria e inicia uma sessao de execucao na nuvem no Jules."""
    logger.info("Criando sessao Jules para source=%s branch=%s", source, branch)
    try:
        req = JulesSessionRequest(
            source=source,
            prompt=prompt,
            branch=branch,
            auto_approve_plan=auto_approve_plan,
        )
        status = client.create_session(req)
        return json.dumps(
            {
                "status": "SUCCESS",
                "sessionId": status.session_id,
                "state": status.state,
                "createTime": status.create_time,
                "updateTime": status.update_time,
                "prUrl": status.pr_url,
                "activities": status.activities or [],
            },
            indent=2,
        )
    except Exception as exc:
        logger.exception("Falha ao criar sessao Jules: %s", exc)
        return json.dumps({"status": "ERROR", "message": str(exc)}, indent=2)


@server.tool(
    name="jules_get_session_status",
    description="Retrieves the current execution status, progress, and pull request info of a Google Jules session.",
)
def jules_get_session_status(
    session_id: str,
    include_activities: bool = True,
) -> str:
    """Consulta o status e o progresso atual de uma sessao."""
    logger.info("Consultando status da sessao=%s", session_id)
    try:
        status = client.get_session_status(
            session_id=session_id,
            include_activities=include_activities,
        )
        return json.dumps(
            {
                "status": "SUCCESS",
                "sessionId": status.session_id,
                "state": status.state,
                "createTime": status.create_time,
                "updateTime": status.update_time,
                "prUrl": status.pr_url,
                "activities": status.activities or [],
            },
            indent=2,
        )
    except Exception as exc:
        logger.exception("Falha ao consultar status da sessao %s: %s", session_id, exc)
        return json.dumps({"status": "ERROR", "message": str(exc)}, indent=2)


@server.tool(
    name="jules_approve_plan",
    description="Approves or rejects a plan generated by Jules during an execution activity.",
)
def jules_approve_plan(
    session_id: str,
    activity_id: str,
    action: str = "APPROVE",
) -> str:
    """Aprova ou rejeita uma atividade de planejamento do Jules."""
    logger.info("Aprovando/rejeitando plano sessao=%s atividade=%s acao=%s", session_id, activity_id, action)
    try:
        success = client.approve_plan(
            session_id=session_id,
            activity_id=activity_id,
            action=action,
        )
        return json.dumps(
            {
                "status": "SUCCESS" if success else "FAILED",
                "sessionId": session_id,
                "activityId": activity_id,
                "action": action,
                "approved": success,
            },
            indent=2,
        )
    except Exception as exc:
        logger.exception("Falha ao aprovar plano %s: %s", activity_id, exc)
        return json.dumps({"status": "ERROR", "message": str(exc)}, indent=2)


@server.tool(
    name="jules_get_diff",
    description="Retrieves the git patch and list of changed files produced by a completed Jules cloud session.",
)
def jules_get_diff(session_id: str) -> str:
    """Coleta o diff unificado gerado pela sessao do Jules."""
    logger.info("Obtendo diff da sessao=%s", session_id)
    try:
        diff_res = client.get_diff(session_id=session_id)
        return json.dumps(
            {
                "status": "SUCCESS",
                "sessionId": diff_res.session_id,
                "filesChanged": diff_res.files_changed,
                "patch": diff_res.diff_content,
            },
            indent=2,
        )
    except Exception as exc:
        logger.exception("Falha ao obter diff da sessao %s: %s", session_id, exc)
        return json.dumps({"status": "ERROR", "message": str(exc)}, indent=2)


@server.tool(
    name="jules_list_sources",
    description="Lists all repository sources connected to Google Jules via the GitHub App integration.",
)
def jules_list_sources(page_size: int = 10, page_token: str = "") -> str:
    """Lista fontes e repositorios autorizados no Google Jules."""
    logger.info("Listando fontes conectadas ao Jules (pageSize=%d)", page_size)
    try:
        sources = client.list_sources(page_size=page_size, page_token=page_token)
        return json.dumps({"status": "SUCCESS", "sources": sources}, indent=2)
    except Exception as exc:
        logger.exception("Falha ao listar fontes do Jules: %s", exc)
        return json.dumps({"status": "ERROR", "message": str(exc)}, indent=2)


@server.tool(
    name="start_new_jules_task",
    description="Starts a new Jules task for a given repository and description.",
)
def start_new_jules_task(repo_name: str, user_task_description: str) -> str:
    """Inicia uma nova tarefa do Jules com formato simplificado de entrada."""
    logger.info("Iniciando nova tarefa Jules repo=%s", repo_name)
    source = f"sources/github/{repo_name}" if not repo_name.startswith("sources/") else repo_name
    return jules_create_session(source=source, prompt=user_task_description)


def main() -> None:
    """Ponto de entrada do servidor stdio MCP."""
    logger.info("Iniciando Google Jules MCP Server no modo STDIO...")
    server.run(transport="stdio")


if __name__ == "__main__":
    main()
