// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { NextRequest } from 'next/server.js';
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js";
import type { AppRouteHandlerRoutes, AppRoutes, LayoutRoutes, ParamMap } from "./routes.js";

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[ Route ]>; } & any> | ( ( props: { params: Promise<ParamMap[ Route ]>; } & any ) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void> );
  generateStaticParams?: ( props: { params: ParamMap[ Route ]; } ) => Promise<any[]> | any[];
  generateMetadata?: (
    props: { params: Promise<ParamMap[ Route ]>; } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any;
  generateViewport?: (
    props: { params: Promise<ParamMap[ Route ]>; } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any;
  metadata?: any;
  viewport?: any;
};

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ( ( props: LayoutProps<Route> ) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void> );
  generateStaticParams?: ( props: { params: ParamMap[ Route ]; } ) => Promise<any[]> | any[];
  generateMetadata?: (
    props: { params: Promise<ParamMap[ Route ]>; } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any;
  generateViewport?: (
    props: { params: Promise<ParamMap[ Route ]>; } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any;
  metadata?: any;
  viewport?: any;
};

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: ( request: NextRequest, context: { params: Promise<ParamMap[ Route ]>; } ) => Promise<Response | void> | Response | void;
  POST?: ( request: NextRequest, context: { params: Promise<ParamMap[ Route ]>; } ) => Promise<Response | void> | Response | void;
  PUT?: ( request: NextRequest, context: { params: Promise<ParamMap[ Route ]>; } ) => Promise<Response | void> | Response | void;
  PATCH?: ( request: NextRequest, context: { params: Promise<ParamMap[ Route ]>; } ) => Promise<Response | void> | Response | void;
  DELETE?: ( request: NextRequest, context: { params: Promise<ParamMap[ Route ]>; } ) => Promise<Response | void> | Response | void;
  HEAD?: ( request: NextRequest, context: { params: Promise<ParamMap[ Route ]>; } ) => Promise<Response | void> | Response | void;
  OPTIONS?: ( request: NextRequest, context: { params: Promise<ParamMap[ Route ]>; } ) => Promise<Response | void> | Response | void;
};


// Validate ../../src/app/ICMlaboratory/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/ICMlaboratory">> = Specific;
  const handler = {} as typeof import( "../../src/app/ICMlaboratory/page.js" );
  type __Check = __IsExpected<typeof handler>;
  // @ts-ignore
  type __Unused = __Check;
}

// Validate ../../src/app/artigos/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/artigos/[slug]">> = Specific;
  const handler = {} as typeof import( "../../src/app/artigos/[slug]/page.js" );
  type __Check = __IsExpected<typeof handler>;
  // @ts-ignore
  type __Unused = __Check;
}

// Validate ../../src/app/artigos/estado-da-arte/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/artigos/estado-da-arte">> = Specific;
  const handler = {} as typeof import( "../../src/app/artigos/estado-da-arte/page.js" );
  type __Check = __IsExpected<typeof handler>;
  // @ts-ignore
  type __Unused = __Check;
}

// Validate ../../src/app/artigos/prospect-theory-icm/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/artigos/prospect-theory-icm">> = Specific;
  const handler = {} as typeof import( "../../src/app/artigos/prospect-theory-icm/page.js" );
  type __Check = __IsExpected<typeof handler>;
  // @ts-ignore
  type __Unused = __Check;
}

// Validate ../../src/app/artigos/psicologia-hs/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/artigos/psicologia-hs">> = Specific;
  const handler = {} as typeof import( "../../src/app/artigos/psicologia-hs/page.js" );
  type __Check = __IsExpected<typeof handler>;
  // @ts-ignore
  type __Unused = __Check;
}

// Validate ../../src/app/artigos/smart-sniper/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/artigos/smart-sniper">> = Specific;
  const handler = {} as typeof import( "../../src/app/artigos/smart-sniper/page.js" );
  type __Check = __IsExpected<typeof handler>;
  // @ts-ignore
  type __Unused = __Check;
}

// Validate ../../src/app/artigos/validacao-smart-sniper/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/artigos/validacao-smart-sniper">> = Specific;
  const handler = {} as typeof import( "../../src/app/artigos/validacao-smart-sniper/page.js" );
  type __Check = __IsExpected<typeof handler>;
  // @ts-ignore
  type __Unused = __Check;
}

// Validate ../../src/app/aulas/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/aulas/[slug]">> = Specific;
  const handler = {} as typeof import( "../../src/app/aulas/[slug]/page.js" );
  type __Check = __IsExpected<typeof handler>;
  // @ts-ignore
  type __Unused = __Check;
}

// Validate ../../src/app/aulas/conceitos-icm/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/aulas/conceitos-icm">> = Specific;
  const handler = {} as typeof import( "../../src/app/aulas/conceitos-icm/page.js" );
  type __Check = __IsExpected<typeof handler>;
  // @ts-ignore
  type __Unused = __Check;
}

// Validate ../../src/app/aulas/icm-masterclass/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/aulas/icm-masterclass">> = Specific;
  const handler = {} as typeof import( "../../src/app/aulas/icm-masterclass/page.js" );
  type __Check = __IsExpected<typeof handler>;
  // @ts-ignore
  type __Unused = __Check;
}

// Validate ../../src/app/aulas/icm-pos-flop/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/aulas/icm-pos-flop">> = Specific;
  const handler = {} as typeof import( "../../src/app/aulas/icm-pos-flop/page.js" );
  type __Check = __IsExpected<typeof handler>;
  // @ts-ignore
  type __Unused = __Check;
}

// Validate ../../src/app/aulas/leitura-icm/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/aulas/leitura-icm">> = Specific;
  const handler = {} as typeof import( "../../src/app/aulas/leitura-icm/page.js" );
  type __Check = __IsExpected<typeof handler>;
  // @ts-ignore
  type __Unused = __Check;
}

// Validate ../../src/app/biblioteca/entendendo-o-icm-e-suas-heuristicas/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/biblioteca/entendendo-o-icm-e-suas-heuristicas">> = Specific;
  const handler = {} as typeof import( "../../src/app/biblioteca/entendendo-o-icm-e-suas-heuristicas/page.js" );
  type __Check = __IsExpected<typeof handler>;
  // @ts-ignore
  type __Unused = __Check;
}

// Validate ../../src/app/biblioteca/estado-da-arte-2025/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/biblioteca/estado-da-arte-2025">> = Specific;
  const handler = {} as typeof import( "../../src/app/biblioteca/estado-da-arte-2025/page.js" );
  type __Check = __IsExpected<typeof handler>;
  // @ts-ignore
  type __Unused = __Check;
}

// Validate ../../src/app/biblioteca/hermeneutica-blefe/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/biblioteca/hermeneutica-blefe">> = Specific;
  const handler = {} as typeof import( "../../src/app/biblioteca/hermeneutica-blefe/page.js" );
  type __Check = __IsExpected<typeof handler>;
  // @ts-ignore
  type __Unused = __Check;
}

// Validate ../../src/app/biblioteca/motor-diluicao/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/biblioteca/motor-diluicao">> = Specific;
  const handler = {} as typeof import( "../../src/app/biblioteca/motor-diluicao/page.js" );
  type __Check = __IsExpected<typeof handler>;
  // @ts-ignore
  type __Unused = __Check;
}

// Validate ../../src/app/biblioteca/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/biblioteca">> = Specific;
  const handler = {} as typeof import( "../../src/app/biblioteca/page.js" );
  type __Check = __IsExpected<typeof handler>;
  // @ts-ignore
  type __Unused = __Check;
}

// Validate ../../src/app/biblioteca/paradoxo-valuation/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/biblioteca/paradoxo-valuation">> = Specific;
  const handler = {} as typeof import( "../../src/app/biblioteca/paradoxo-valuation/page.js" );
  type __Check = __IsExpected<typeof handler>;
  // @ts-ignore
  type __Unused = __Check;
}

// Validate ../../src/app/biblioteca/protocolo-smart-sniper/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/biblioteca/protocolo-smart-sniper">> = Specific;
  const handler = {} as typeof import( "../../src/app/biblioteca/protocolo-smart-sniper/page.js" );
  type __Check = __IsExpected<typeof handler>;
  // @ts-ignore
  type __Unused = __Check;
}

// Validate ../../src/app/biblioteca/psicologia-high-stakes/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/biblioteca/psicologia-high-stakes">> = Specific;
  const handler = {} as typeof import( "../../src/app/biblioteca/psicologia-high-stakes/page.js" );
  type __Check = __IsExpected<typeof handler>;
  // @ts-ignore
  type __Unused = __Check;
}

// Validate ../../src/app/biblioteca/teoria-da-perspectiva/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/biblioteca/teoria-da-perspectiva">> = Specific;
  const handler = {} as typeof import( "../../src/app/biblioteca/teoria-da-perspectiva/page.js" );
  type __Check = __IsExpected<typeof handler>;
  // @ts-ignore
  type __Unused = __Check;
}

// Validate ../../src/app/biblioteca/voce-aprende-poker-errado/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/biblioteca/voce-aprende-poker-errado">> = Specific;
  const handler = {} as typeof import( "../../src/app/biblioteca/voce-aprende-poker-errado/page.js" );
  type __Check = __IsExpected<typeof handler>;
  // @ts-ignore
  type __Unused = __Check;
}

// Validate ../../src/app/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard">> = Specific;
  const handler = {} as typeof import( "../../src/app/dashboard/page.js" );
  type __Check = __IsExpected<typeof handler>;
  // @ts-ignore
  type __Unused = __Check;
}

// Validate ../../src/app/laboratorio-v2/gto-cfr/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/laboratorio-v2/gto-cfr">> = Specific;
  const handler = {} as typeof import( "../../src/app/laboratorio-v2/gto-cfr/page.js" );
  type __Check = __IsExpected<typeof handler>;
  // @ts-ignore
  type __Unused = __Check;
}

// Validate ../../src/app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific;
  const handler = {} as typeof import( "../../src/app/page.js" );
  type __Check = __IsExpected<typeof handler>;
  // @ts-ignore
  type __Unused = __Check;
}

// Validate ../../src/app/quem-sou/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/quem-sou">> = Specific;
  const handler = {} as typeof import( "../../src/app/quem-sou/page.js" );
  type __Check = __IsExpected<typeof handler>;
  // @ts-ignore
  type __Unused = __Check;
}

// Validate ../../src/app/simulador/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/simulador">> = Specific;
  const handler = {} as typeof import( "../../src/app/simulador/page.js" );
  type __Check = __IsExpected<typeof handler>;
  // @ts-ignore
  type __Unused = __Check;
}

// Validate ../../src/app/templo/analytics/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/templo/analytics">> = Specific;
  const handler = {} as typeof import( "../../src/app/templo/analytics/page.js" );
  type __Check = __IsExpected<typeof handler>;
  // @ts-ignore
  type __Unused = __Check;
}

// Validate ../../src/app/api/og/route.tsx
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/og">> = Specific;
  const handler = {} as typeof import( "../../src/app/api/og/route.js" );
  type __Check = __IsExpected<typeof handler>;
  // @ts-ignore
  type __Unused = __Check;
}

// Validate ../../src/app/api/rag/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/rag">> = Specific;
  const handler = {} as typeof import( "../../src/app/api/rag/route.js" );
  type __Check = __IsExpected<typeof handler>;
  // @ts-ignore
  type __Unused = __Check;
}

// Validate ../../src/app/api/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api">> = Specific;
  const handler = {} as typeof import( "../../src/app/api/route.js" );
  type __Check = __IsExpected<typeof handler>;
  // @ts-ignore
  type __Unused = __Check;
}

// Validate ../../src/app/api/telemetry/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/telemetry">> = Specific;
  const handler = {} as typeof import( "../../src/app/api/telemetry/route.js" );
  type __Check = __IsExpected<typeof handler>;
  // @ts-ignore
  type __Unused = __Check;
}





// Validate ../../src/app/aulas/icm-masterclass/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/aulas/icm-masterclass">> = Specific;
  const handler = {} as typeof import( "../../src/app/aulas/icm-masterclass/layout.js" );
  type __Check = __IsExpected<typeof handler>;
  // @ts-ignore
  type __Unused = __Check;
}

// Validate ../../src/app/biblioteca/voce-aprende-poker-errado/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/biblioteca/voce-aprende-poker-errado">> = Specific;
  const handler = {} as typeof import( "../../src/app/biblioteca/voce-aprende-poker-errado/layout.js" );
  type __Check = __IsExpected<typeof handler>;
  // @ts-ignore
  type __Unused = __Check;
}

// Validate ../../src/app/laboratorio-v2/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/laboratorio-v2">> = Specific;
  const handler = {} as typeof import( "../../src/app/laboratorio-v2/layout.js" );
  type __Check = __IsExpected<typeof handler>;
  // @ts-ignore
  type __Unused = __Check;
}

// Validate ../../src/app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific;
  const handler = {} as typeof import( "../../src/app/laboratorio-v2/gto-cfr/layout.js" );
  type __Check = __IsExpected<typeof handler>;
  // @ts-ignore
  type __Unused = __Check;
}
