// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { NextRequest } from 'next/server.js'
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { AppRouteHandlerRoutes, AppRoutes, LayoutRoutes, ParamMap } from "./routes.js"

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<any> | ( ( props: any ) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void> )
  generateStaticParams?: ( props: { params: ParamMap[ Route ] } ) => Promise<any[]> | any[]
  generateMetadata?: (
    props: any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ( ( props: LayoutProps<Route> ) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void> )
  generateStaticParams?: ( props: { params: ParamMap[ Route ] } ) => Promise<any[]> | any[]
  generateMetadata?: (
    props: any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: ( request: NextRequest, context: { params: Promise<ParamMap[ Route ]> } ) => Promise<Response | void> | Response | void
  POST?: ( request: NextRequest, context: { params: Promise<ParamMap[ Route ]> } ) => Promise<Response | void> | Response | void
  PUT?: ( request: NextRequest, context: { params: Promise<ParamMap[ Route ]> } ) => Promise<Response | void> | Response | void
  PATCH?: ( request: NextRequest, context: { params: Promise<ParamMap[ Route ]> } ) => Promise<Response | void> | Response | void
  DELETE?: ( request: NextRequest, context: { params: Promise<ParamMap[ Route ]> } ) => Promise<Response | void> | Response | void
  HEAD?: ( request: NextRequest, context: { params: Promise<ParamMap[ Route ]> } ) => Promise<Response | void> | Response | void
  OPTIONS?: ( request: NextRequest, context: { params: Promise<ParamMap[ Route ]> } ) => Promise<Response | void> | Response | void
}


// Validate ../../../src/app/artigos/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/artigos/[slug]">> = Specific
  const handler = {} as typeof import( "../../../src/app/artigos/[slug]/page.js" )
  // @ts-ignore
  type __Check = __IsExpected<typeof handler>
}

// Validate ../../../src/app/artigos/estado-da-arte/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/artigos/estado-da-arte">> = Specific
  const handler = {} as typeof import( "../../../src/app/artigos/estado-da-arte/page.js" )
  // @ts-ignore
  type __Check = __IsExpected<typeof handler>
}

// Validate ../../../src/app/artigos/psicologia-hs/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/artigos/psicologia-hs">> = Specific
  const handler = {} as typeof import( "../../../src/app/artigos/psicologia-hs/page.js" )
  // @ts-ignore
  type __Check = __IsExpected<typeof handler>
}

// Validate ../../../src/app/artigos/smart-sniper/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/artigos/smart-sniper">> = Specific
  const handler = {} as typeof import( "../../../src/app/artigos/smart-sniper/page.js" )
  // @ts-ignore
  type __Check = __IsExpected<typeof handler>
}

// Validate ../../../src/app/artigos/validacao-smart-sniper/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/artigos/validacao-smart-sniper">> = Specific
  const handler = {} as typeof import( "../../../src/app/artigos/validacao-smart-sniper/page.js" )
  // @ts-ignore
  type __Check = __IsExpected<typeof handler>
}

// Validate ../../../src/app/aulas/conceitos-icm/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/aulas/conceitos-icm">> = Specific
  const handler = {} as typeof import( "../../../src/app/aulas/conceitos-icm/page.js" )
  // @ts-ignore
  type __Check = __IsExpected<typeof handler>
}

// Validate ../../../src/app/aulas/icm-masterclass/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/aulas/icm-masterclass">> = Specific
  const handler = {} as typeof import( "../../../src/app/aulas/icm-masterclass/page.js" )
  // @ts-ignore
  type __Check = __IsExpected<typeof handler>
}

// Validate ../../../src/app/aulas/icm-pos-flop/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/aulas/icm-pos-flop">> = Specific
  const handler = {} as typeof import( "../../../src/app/aulas/icm-pos-flop/page.js" )
  // @ts-ignore
  type __Check = __IsExpected<typeof handler>
}

// Validate ../../../src/app/aulas/leitura-icm/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/aulas/leitura-icm">> = Specific
  const handler = {} as typeof import( "../../../src/app/aulas/leitura-icm/page.js" )
  // @ts-ignore
  type __Check = __IsExpected<typeof handler>
}

// Validate ../../../src/app/biblioteca/entendendo-o-icm-e-suas-heuristicas/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/biblioteca/entendendo-o-icm-e-suas-heuristicas">> = Specific
  const handler = {} as typeof import( "../../../src/app/biblioteca/entendendo-o-icm-e-suas-heuristicas/page.js" )
  // @ts-ignore
  type __Check = __IsExpected<typeof handler>
}

// Validate ../../../src/app/biblioteca/hermeneutica-blefe/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/biblioteca/hermeneutica-blefe">> = Specific
  const handler = {} as typeof import( "../../../src/app/biblioteca/hermeneutica-blefe/page.js" )
  // @ts-ignore
  type __Check = __IsExpected<typeof handler>
}

// Validate ../../../src/app/biblioteca/motor-diluicao/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/biblioteca/motor-diluicao">> = Specific
  const handler = {} as typeof import( "../../../src/app/biblioteca/motor-diluicao/page.js" )
  // @ts-ignore
  type __Check = __IsExpected<typeof handler>
}

// Validate ../../../src/app/biblioteca/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/biblioteca">> = Specific
  const handler = {} as typeof import( "../../../src/app/biblioteca/page.js" )
  // @ts-ignore
  type __Check = __IsExpected<typeof handler>
}

// Validate ../../../src/app/biblioteca/paradoxo-valuation/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/biblioteca/paradoxo-valuation">> = Specific
  const handler = {} as typeof import( "../../../src/app/biblioteca/paradoxo-valuation/page.js" )
  // @ts-ignore
  type __Check = __IsExpected<typeof handler>
}

// Validate ../../../src/app/biblioteca/voce-aprende-poker-errado/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/biblioteca/voce-aprende-poker-errado">> = Specific
  const handler = {} as typeof import( "../../../src/app/biblioteca/voce-aprende-poker-errado/page.js" )
  // @ts-ignore
  type __Check = __IsExpected<typeof handler>
}

// Validate ../../../src/app/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard">> = Specific
  const handler = {} as typeof import( "../../../src/app/dashboard/page.js" )
  // @ts-ignore
  type __Check = __IsExpected<typeof handler>
}

// Validate ../../../src/app/laboratorio-icm/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/laboratorio-icm">> = Specific
  const handler = {} as typeof import( "../../../src/app/laboratorio-icm/page.js" )
  // @ts-ignore
  type __Check = __IsExpected<typeof handler>
}

// Validate ../../../src/app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import( "../../../src/app/page.js" )
  // @ts-ignore
  type __Check = __IsExpected<typeof handler>
}

// Validate ../../../src/app/quem-sou/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/quem-sou">> = Specific
  const handler = {} as typeof import( "../../../src/app/quem-sou/page.js" )
  // @ts-ignore
  type __Check = __IsExpected<typeof handler>
}

// Validate ../../../src/app/simulador/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/simulador">> = Specific
  const handler = {} as typeof import( "../../../src/app/simulador/page.js" )
  // @ts-ignore
  type __Check = __IsExpected<typeof handler>
}

// Validate ../../../src/app/templo/analytics/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/templo/analytics">> = Specific
  const handler = {} as typeof import( "../../../src/app/templo/analytics/page.js" )
  // @ts-ignore
  type __Check = __IsExpected<typeof handler>
}

// Validate ../../../src/app/api/og/route.tsx
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/og">> = Specific
  const handler = {} as typeof import( "../../../src/app/api/og/route.js" )
  // @ts-ignore
  type __Check = __IsExpected<typeof handler>
}

// Validate ../../../src/app/api/rag/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/rag">> = Specific
  const handler = {} as typeof import( "../../../src/app/api/rag/route.js" )
  // @ts-ignore
  type __Check = __IsExpected<typeof handler>
}

// Validate ../../../src/app/api/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api">> = Specific
  const handler = {} as typeof import( "../../../src/app/api/route.js" )
  // @ts-ignore
  type __Check = __IsExpected<typeof handler>
}





// Validate ../../../src/app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import( "../../../src/app/layout.js" )
  // @ts-ignore
  type __Check = __IsExpected<typeof handler>
}
