/**
 * IDENTITY: Base de Dados dos Cenários Clínicos de ICM Quantum (v4.1)
 * PATH: src/components/simulator/engine/scenarios.ts
 * ROLE: Fonte de verdade com densidade total de mesa (9 players) para garantir pressão ICM real.
 */

import type { Scenario } from './types';

// Referencial de Prêmios da Aula 1.2 (Âncora empírica: 126 jogadores, TOTAL_POOL = $1234.80)
const FT_PRIZES = [ 237.34, 170.96, 135.17, 109.99, 90.28, 73.95, 59.92, 47.56, 36.47 ];

export const SCENARIOS: Scenario[] = [
  {
    id: 'chipev',
    name: 'Vácuo Matemático',
    category: 'baseline',
    stacks: [ 100, 100 ],
    prizes: [ 408.3 ],
    ipRp: 0, oopRp: 0,
    ipPos: 'BTN', oopPos: 'BB',
    ipMorph: 'Polar Perfeito', oopMorph: 'Defesa Base',
    verdict: 'MDF Perfeito',
    narrativeTitle: 'O Equilíbrio Linear',
    narrativeSubtitle: 'ChipEV Puro (Referencial 0)',
    icon: 'fa-gear', color: 'slate',
    theory: `Referencial zero. A utilidade das fichas é linear — cada chip vale exatamente 1 chip, sem assimetria. O MDF é cumprido com exatidão porque não há pressão externa. Todo desvio do Alpha (frequência mínima de defesa) é punido imediatamente pelo oponente racional: se você folda demais, ele blefa mais; se você defende demais, ele corta blefes.`,
    exploit: [ 'Referencial Zero: Use para calibrar sua percepção básica.', 'Compare: qualquer cenário com RP > 0 mostra quanto o ICM distorce esse equilíbrio linear.' ],
    sprData: [ { name: 'PRE', potSize: 2.5, rpValue: 0 }, { name: 'FLOP', potSize: 7.5, rpValue: 0 }, { name: 'TURN', potSize: 22.5, rpValue: 0 }, { name: 'RIVER', potSize: 67.5, rpValue: 0 } ],
    defaultStreetFreqs: {
      flop: { ip_check: 40, ip_bet_small: 35, ip_bet_large: 25, oop_call: 50, oop_fold: 40, oop_raise: 10 },
      turn: { ip_check: 35, ip_bet_small: 30, ip_bet_large: 35, oop_call: 55, oop_fold: 35, oop_raise: 10 },
      river: { ip_check: 30, ip_bet_small: 10, ip_bet_large: 60, oop_call: 65, oop_fold: 28, oop_raise: 7 },
    },
    quiz: { question: 'Por que no ChipEV puro o desvio do Alpha é punido imediatamente?', options: [ { id: 'A', text: 'Porque não há overfold — o oponente ajusta com precisão.', isCorrect: true }, { id: 'B', text: 'Porque as fichas valem mais quando perdidas.', isCorrect: false }, { id: 'C', text: 'Porque o MDF é impossível de cumprir.', isCorrect: false }, { id: 'D', text: 'Porque o ICM penaliza desvios.', isCorrect: false } ], explanation: 'Em ChipEV, cada chip vale 1 chip. Sem assimetria de valor, não há overfold estrutural — o oponente racional explora qualquer desvio do Alpha imediatamente.' }
  },
  {
    id: 'icmev-puro',
    name: 'ICMev (A Fotografia)',
    category: 'baseline',
    stacks: [ 25, 25, 5, 40, 12, 10, 8, 15, 60 ],
    prizes: FT_PRIZES,
    ipRp: 18.5, oopRp: 18.5,
    ipPos: 'Mid', oopPos: 'Mid',
    ipMorph: 'Valor Estrito', oopMorph: 'Condensado',
    verdict: 'Pressão Estática',
    narrativeTitle: 'O Dogma do EV Fold = 0',
    narrativeSubtitle: 'ICM Tradicional',
    icon: 'fa-camera', color: 'blue',
    theory: `O ICM EV calcula o valor monetário da stack <em>como se o torneio terminasse agora</em>. É um snapshot financeiro — correto no instante, mas cego para o fluxo. Não captura o salto de blinds iminente, a posição na próxima mão, nem o impacto futuro de ganhar ou perder o pot. O EV_fold é tratado como zero, quando na realidade pode ser positivo (payjumps passivos) ou violentamente negativo (pot entrapment pós-flop). É a base necessária, mas insuficiente.`,
    exploit: [ 'Identifique a Rigidez: O modelo ignora blinds subindo e posição futura.', 'O EV_fold nunca é zero em torneios — use o threshold correto.' ],
    sprData: [ { name: 'PRE', potSize: 2.5, rpValue: 18.5 }, { name: 'FLOP', potSize: 7.5, rpValue: 14.2 }, { name: 'TURN', potSize: 22.5, rpValue: 8.4 }, { name: 'RIVER', potSize: 25, rpValue: 3.1 } ],
    defaultStreetFreqs: {
      flop: { ip_check: 30, ip_bet_small: 50, ip_bet_large: 20, oop_call: 45, oop_fold: 45, oop_raise: 10 },
      turn: { ip_check: 25, ip_bet_small: 40, ip_bet_large: 35, oop_call: 50, oop_fold: 40, oop_raise: 10 },
      river: { ip_check: 20, ip_bet_small: 15, ip_bet_large: 65, oop_call: 60, oop_fold: 33, oop_raise: 7 },
    },
    quiz: { question: 'Qual a falha fundamental do ICM EV puro?', options: [ { id: 'A', text: 'Trata o torneio como se terminasse na mão atual.', isCorrect: true }, { id: 'B', text: 'Calcula o valor das fichas de forma incorreta.', isCorrect: false }, { id: 'C', text: 'Não considera a estrutura de pagamentos.', isCorrect: false }, { id: 'D', text: 'Ignora a posição na mesa.', isCorrect: false } ], explanation: 'O ICM EV é um snapshot: calcula corretamente o valor do pot, mas como se o torneio parasse ali. Não captura cadeia futura (blinds subindo, posição na próxima mão, FGS).' }
  },
  {
    id: 'paradoxo',
    name: 'Paradoxo do Valuation',
    category: 'clinical',
    stacks: [ 40, 55, 9.4, 52.4, 22.2, 7, 44.3, 24.3, 13.4 ],
    prizes: FT_PRIZES,
    ipRp: 21.4, oopRp: 12.9,
    ipPos: 'BTN', oopPos: 'BB (CL)',
    ipMorph: 'Valor Estrito', oopMorph: 'Condensado',
    verdict: 'Agressão Estrangulada',
    narrativeTitle: 'A Assimetria de Sobrevivência',
    narrativeSubtitle: 'Mid vs Big Stack',
    icon: 'fa-scale-unbalanced', color: 'rose',
    theory: `O BTN (40bb, RP 21.4%) paga mais caro por cada erro do que o BB (55bb, RP 12.9%). A assimetria de ΔRP (+8.5pp a favor do BB) permite ao BB ser mais agressivo — ele pode absorver perdas que destruiriam o BTN. Os hero-bluffs do BTN custam mais em $EV do que valem: a agressão é estrangulada pelo próprio RP do agressor. O overfold do BTN não é fraqueza — é equilíbrio estrutural.`,
    exploit: [ 'Aceite o overfold estratégico como BTN.', 'Como BB: explore com thin value — o BTN não pode punir.' ],
    sprData: [ { name: 'PRE', potSize: 2.5, rpValue: 12.9 }, { name: 'FLOP', potSize: 7.5, rpValue: 10.4 }, { name: 'TURN', potSize: 22.5, rpValue: 5.8 }, { name: 'RIVER', potSize: 40, rpValue: 2.6 } ],
    defaultStreetFreqs: {
      flop: { ip_check: 2, ip_bet_small: 65, ip_bet_large: 33, oop_call: 45, oop_fold: 40, oop_raise: 15 },
      turn: { ip_check: 20, ip_bet_small: 45, ip_bet_large: 35, oop_call: 55, oop_fold: 35, oop_raise: 10 },
      river: { ip_check: 35, ip_bet_small: 10, ip_bet_large: 55, oop_call: 65, oop_fold: 28, oop_raise: 7 },
    },
    quiz: { question: 'Por que o BTN sofre mais neste confronto?', options: [ { id: 'A', text: 'RP maior (21.4%) significa que cada chip perdido vale mais em $EV.', isCorrect: true }, { id: 'B', text: 'Porque está fora de posição.', isCorrect: false }, { id: 'C', text: 'Porque o BB tem cartas melhores.', isCorrect: false }, { id: 'D', text: 'Porque o pot é grande demais.', isCorrect: false } ], explanation: 'A assimetria de RP (21.4% vs 12.9%) cria um ΔRP de +8.5pp a favor do BB. O BTN arrisca proporcionalmente mais por cada ficha investida — a dor da perda é estruturalmente maior.' }
  },
  {
    id: 'pacto',
    name: 'Pacto Silencioso',
    category: 'clinical',
    stacks: [ 65, 70, 9.4, 52.4, 22.2, 7, 44.3, 24.3, 13.4 ],
    prizes: FT_PRIZES,
    ipRp: 24.5, oopRp: 23.5,
    ipPos: 'Vice CL', oopPos: 'CL',
    ipMorph: 'Polar Controlado', oopMorph: 'Inelástico',
    verdict: 'Evitação de Ruína',
    narrativeTitle: 'A Mútua Destruição Assegurada',
    narrativeSubtitle: 'Colisão de Gigantes',
    icon: 'fa-handshake', color: 'indigo',
    theory: `Vice CL (65bb, RP 24.5%) vs CL (70bb, RP 23.5%). Ambos carregam RP acima de 20% — zona onde 3-bets e overbets se tornam suicídio mútuo. A Perspectiva de ambos é alta; qualquer colisão all-in destrói a posição de quem perder e danifica a de quem ganhar (pelo Risco de Ressurreição do rival). O Pacto Silencioso é a passividade mútua racional: calls substituem raises, bets encolhem, e a guerra se limita a potes controlados.`,
    exploit: [ 'Supressão de 3-bet: Transforme valor em calls.', 'Small bets dominam — large bets são vetadas pelo RP mútuo.' ],
    sprData: [ { name: 'PRE', potSize: 2.5, rpValue: 23.5 }, { name: 'FLOP', potSize: 8, rpValue: 22 }, { name: 'TURN', potSize: 24, rpValue: 14.7 }, { name: 'RIVER', potSize: 65, rpValue: 11.8 } ],
    defaultStreetFreqs: {
      flop: { ip_check: 35, ip_bet_small: 40, ip_bet_large: 25, oop_call: 50, oop_fold: 35, oop_raise: 15 },
      turn: { ip_check: 25, ip_bet_small: 35, ip_bet_large: 40, oop_call: 55, oop_fold: 33, oop_raise: 12 },
      river: { ip_check: 20, ip_bet_small: 10, ip_bet_large: 70, oop_call: 65, oop_fold: 28, oop_raise: 7 },
    },
    quiz: { question: 'O que causa o Pacto Silencioso entre gigantes?', options: [ { id: 'A', text: 'RP mútuo alto (>20%) torna agressão binária suicida para ambos.', isCorrect: true }, { id: 'B', text: 'Acordo verbal entre jogadores.', isCorrect: false }, { id: 'C', text: 'Ambos têm ranges fracos nessa posição.', isCorrect: false }, { id: 'D', text: 'O pot é pequeno demais para justificar ação.', isCorrect: false } ], explanation: 'Com RP acima de 20% para ambos, a Perspectiva de cada gigante é alta demais para arriscar em confrontos binários. A passividade mútua é equilíbrio racional — choque direto aniquila a Esperança do perdedor.' }
  },
  {
    id: 'batata',
    name: 'Efeito Batata Quente',
    category: 'clinical',
    stacks: [ 25, 20, 5, 40, 12, 10, 8, 15, 60 ],
    prizes: FT_PRIZES,
    ipRp: 15, oopRp: 19.5,
    ipPos: 'UTG', oopPos: 'BB',
    ipMorph: 'Push Estendido', oopMorph: 'Condensado Extremo',
    verdict: 'Transferência de Fardo',
    narrativeTitle: 'O Peso de Agir Primeiro',
    narrativeSubtitle: 'A Dinâmica do Shove',
    icon: 'fa-fire-flame-curved', color: 'amber',
    theory: `O open-shove de 20bb não é apenas uma aposta — é uma <strong>transferência de peso volitivo</strong>. O agressor acopla Fold Equity ao RP e retira do BB a capacidade de re-agressão. O defensor colapsa para overfold matemático forçado pelo custo binário da eliminação. O BB (RP 19.5%) precisa de equity significativamente acima dos pot odds para justificar o call — o "fardo" do ICM é transferido inteiramente para quem defende.`,
    exploit: [ 'Alpha Real: Expanda o range de shove até o teto matemático.', 'O defensor carrega o fardo — cada mão que ele folda é lucro estrutural.' ],
    sprData: [ { name: 'PRE', potSize: 2.5, rpValue: 19.5 }, { name: 'FLOP', potSize: 7, rpValue: 13 }, { name: 'TURN', potSize: 14, rpValue: 5.5 }, { name: 'RIVER', potSize: 20, rpValue: 1.9 } ],
    defaultStreetFreqs: {
      flop: { ip_check: 0, ip_bet_small: 0, ip_bet_large: 100, oop_call: 40, oop_fold: 60, oop_raise: 0 },
      turn: { ip_check: 0, ip_bet_small: 0, ip_bet_large: 100, oop_call: 42, oop_fold: 58, oop_raise: 0 },
      river: { ip_check: 0, ip_bet_small: 0, ip_bet_large: 100, oop_call: 45, oop_fold: 55, oop_raise: 0 },
    },
    quiz: { question: 'Qual o mecanismo central do open-shove em ICM?', options: [ { id: 'A', text: 'Transfere o fardo do ICM para o defensor, que colapsa em overfold.', isCorrect: true }, { id: 'B', text: 'Maximiza o valor esperado das fichas ganhas.', isCorrect: false }, { id: 'C', text: 'Impede que o oponente veja o flop.', isCorrect: false }, { id: 'D', text: 'Reduz a variância do resultado.', isCorrect: false } ], explanation: 'O shove transfere o peso volitivo: o agressor impõe uma decisão binária (tudo ou nada) ao defensor, que carrega RP alto e é forçado ao overfold estrutural. A Fold Equity em ICM é exponencialmente mais poderosa que em ChipEV.' }
  },
  {
    id: 'agonia',
    name: 'Agonia do Bluffcatcher',
    category: 'clinical',
    stacks: [ 80, 30, 5, 40, 12, 10, 8, 15, 60 ],
    prizes: FT_PRIZES,
    ipRp: 4.5, oopRp: 22,
    ipPos: 'CL', oopPos: 'Mid',
    ipMorph: 'Modo Predador', oopMorph: 'Bluffcatcher',
    verdict: 'MDF Quebrado',
    narrativeTitle: 'O Colapso do MDF',
    narrativeSubtitle: 'Condensado vs Polar',
    icon: 'fa-heart-crack', color: 'sky',
    theory: `O CL (80bb, RP 4.5%) enfrenta o Mid (30bb, RP 22%). O MDF do Mid exigiria defesa de ~67% dos bluffs, mas sob RP de 22%, a defesa real colapsa. O Mid precisa de equity muito acima do breakeven para justificar calls — o "bluffcatcher" que em ChipEV seria lucrativo torna-se insolvente. O CL pode overbluffar sistematicamente porque o custo da perda para ele é mínimo (RP 4.5%) enquanto o custo do call para o Mid é catastrófico.`,
    exploit: [ 'Overbluff Sistemático: o defensor é inelástico.', 'Thin value agressivo: o Mid não pode punir com raise.' ],
    sprData: [ { name: 'PRE', potSize: 2.5, rpValue: 22 }, { name: 'FLOP', potSize: 8, rpValue: 16.4 }, { name: 'TURN', potSize: 24, rpValue: 5.3 }, { name: 'RIVER', potSize: 30, rpValue: 2.2 } ],
    defaultStreetFreqs: {
      flop: { ip_check: 20, ip_bet_small: 30, ip_bet_large: 50, oop_call: 50, oop_fold: 40, oop_raise: 10 },
      turn: { ip_check: 15, ip_bet_small: 20, ip_bet_large: 65, oop_call: 60, oop_fold: 33, oop_raise: 7 },
      river: { ip_check: 10, ip_bet_small: 5, ip_bet_large: 85, oop_call: 72, oop_fold: 22, oop_raise: 6 },
    },
    quiz: { question: 'Por que o MDF do Mid-stack quebra contra o CL?', options: [ { id: 'A', text: 'RP de 22% eleva o custo de cada call acima do breakeven do MDF.', isCorrect: true }, { id: 'B', text: 'Porque o CL tem cartas melhores.', isCorrect: false }, { id: 'C', text: 'Porque o Mid não tem fichas suficientes para pagar.', isCorrect: false }, { id: 'D', text: 'Porque o pot é muito pequeno.', isCorrect: false } ], explanation: 'Com RP de 22%, cada chip arriscado pelo Mid vale mais em $EV do que o ganho potencial. O MDF teórico exigiria defesa ampla, mas o custo ICM de estar errado é tão alto que o overfold se torna o equilíbrio real.' }
  },
  {
    id: 'lama',
    name: 'Guerra na Lama',
    category: 'clinical',
    stacks: [ 12, 10, 80, 70, 60, 50, 40, 30, 20 ],
    prizes: FT_PRIZES,
    ipRp: 8.5, oopRp: 7.5,
    ipPos: 'Micro', oopPos: 'Micro',
    ipMorph: 'Especulativo', oopMorph: 'Call Seletivo',
    verdict: 'Fome de Laddering',
    narrativeTitle: 'O Minitorneio de Sobrevivência',
    narrativeSubtitle: 'Micro vs Micro',
    icon: 'fa-person-falling-burst', color: 'emerald',
    theory: `Dois micro-stacks (12bb e 10bb) com RP baixo (8.5% e 7.5%) — paradoxalmente, a Perspectiva deles é mínima a proteger. Mas gigantes na mesa (80bb, 70bb, 60bb) elevam o EV do fold: cada eliminação de outro short gera payjumps passivos sem investimento. O "minitorneio de sobrevivência" entre shorts não é sobre ganhar fichas — é sobre outlasting. Quem joga ChipEV aqui sangra equity sistêmica.`,
    exploit: [ 'Cada vizinho moribundo que cai vale um payjump gratuito.', 'Evite colisões entre shorts — o EV do fold pode ser positivo.' ],
    sprData: [ { name: 'PRE', potSize: 2.5, rpValue: 7.5 }, { name: 'FLOP', potSize: 6, rpValue: 4.5 }, { name: 'TURN', potSize: 10, rpValue: 1.5 }, { name: 'RIVER', potSize: 12, rpValue: 0.9 } ],
    defaultStreetFreqs: {
      flop: { ip_check: 40, ip_bet_small: 35, ip_bet_large: 25, oop_call: 50, oop_fold: 38, oop_raise: 12 },
      turn: { ip_check: 35, ip_bet_small: 30, ip_bet_large: 35, oop_call: 55, oop_fold: 35, oop_raise: 10 },
      river: { ip_check: 30, ip_bet_small: 10, ip_bet_large: 60, oop_call: 65, oop_fold: 28, oop_raise: 7 },
    },
    quiz: { question: 'Por que shorts com gigantes na mesa devem evitar colisão?', options: [ { id: 'A', text: 'O EV do fold é positivo — payjumps passivos superam o ganho de fichas.', isCorrect: true }, { id: 'B', text: 'Porque os shorts não têm fichas suficientes para ganhar.', isCorrect: false }, { id: 'C', text: 'Porque o ICM não se aplica a stacks pequenos.', isCorrect: false }, { id: 'D', text: 'Porque os gigantes sempre intervêm.', isCorrect: false } ], explanation: 'Com múltiplos shorts na mesa e gigantes dominantes, cada eliminação de outro jogador gera payjumps passivos. Foldar pode literalmente gerar lucro — o EV do fold é positivo em ICM.' }
  },
  {
    id: 'ameaca',
    name: 'Ameaça Orgânica',
    category: 'clinical',
    stacks: [ 90, 25, 20, 18, 15, 12, 10, 8, 5 ],
    prizes: FT_PRIZES,
    ipRp: 12, oopRp: 21,
    ipPos: 'CL', oopPos: 'Vice',
    ipMorph: 'Polar Controlado', oopMorph: 'Inelástico',
    verdict: 'Criação de Monstros',
    narrativeTitle: 'O Limite do God Mode',
    narrativeSubtitle: 'Dominância Absoluta',
    icon: 'fa-crown', color: 'fuchsia',
    theory: `O CL (90bb, RP 12%) parece invencível, mas carrega um risco orgânico: dobrar o vice (25bb → 50bb) <strong>devolve a complexidade da árvore de decisão ao oponente</strong> (Risco de Ressurreição). O vice com 50bb ganha ferramentas (3bet, float, multi-barrel) que com 25bb não tinha. Paradoxalmente, o CL deve extrair thin value agressivo de quem se auto-restringe pelo RP, mas evitar confrontos que criem um rival com arsenal restaurado.`,
    exploit: [ 'Thin Value Mandatório: extraia de quem se auto-restringe.', 'Cuidado com Ressurreição: dobrar o vice cria um rival perigoso.' ],
    sprData: [ { name: 'PRE', potSize: 2.5, rpValue: 21 }, { name: 'FLOP', potSize: 7.5, rpValue: 14.5 }, { name: 'TURN', potSize: 22.5, rpValue: 1.9 }, { name: 'RIVER', potSize: 25, rpValue: 1.2 } ],
    defaultStreetFreqs: {
      flop: { ip_check: 25, ip_bet_small: 40, ip_bet_large: 35, oop_call: 50, oop_fold: 38, oop_raise: 12 },
      turn: { ip_check: 20, ip_bet_small: 30, ip_bet_large: 50, oop_call: 55, oop_fold: 35, oop_raise: 10 },
      river: { ip_check: 15, ip_bet_small: 10, ip_bet_large: 75, oop_call: 65, oop_fold: 28, oop_raise: 7 },
    },
    quiz: { question: 'Qual o risco oculto do CL ao confrontar o vice?', options: [ { id: 'A', text: 'Ressurreição: dobrar o vice restaura ferramentas estratégicas que ele não tinha.', isCorrect: true }, { id: 'B', text: 'O CL perde automaticamente contra o vice.', isCorrect: false }, { id: 'C', text: 'O RP do CL é sempre maior que o do vice.', isCorrect: false }, { id: 'D', text: 'O prize pool diminui se o CL perder.', isCorrect: false } ], explanation: 'Dobrar um stack de 25bb para 50bb devolve complexidade ao oponente: 3bet, float, multi-barrel — ferramentas que estavam inacessíveis. O ganho imediato de fichas pode ser inferior ao custo sistêmico de criar um rival com arsenal restaurado.' }
  },
  {
    id: 'especulacao',
    name: 'Especulação Assimétrica',
    category: 'clinical',
    stacks: [ 35, 80, 12, 10, 8, 7, 6, 5, 4 ],
    prizes: FT_PRIZES,
    ipRp: 38, oopRp: 8.2,
    ipPos: 'BTN (Mid)', oopPos: 'BB (CL)',
    ipMorph: 'Especulativo', oopMorph: 'Call Seletivo',
    verdict: 'Implied Odds de ICM',
    narrativeTitle: 'O Parasita Silencioso',
    narrativeSubtitle: 'Mid-Stack vs Chip Leader',
    icon: 'fa-virus', color: 'fuchsia',
    theory: `O Mid (35bb, RP 38%) especula contra o CL (80bb, RP 8.2%) com custo controlado. O investimento é pequeno (flat call, não 3-bet), mas se acertar, a Expectativa explode: vira o novo CL, mitiga o principal adversário, e ganha leverage futuro. As Implied Odds aqui são de ICM, não de pot — o ganho não é medido em fichas, mas em ΔPerspectiva. O CL perde RP mínimo se o Mid acertar; o Mid ganha ferramentas de pressão amplificadas.`,
    exploit: [ 'Implied Odds de ICM: pague pouco para monsterizar.', 'Flat > 3bet: controle o custo de entrada.' ],
    sprData: [ { name: 'PRE', potSize: 2.5, rpValue: 8.2 }, { name: 'FLOP', potSize: 7, rpValue: 6.8 }, { name: 'TURN', potSize: 18, rpValue: 3.5 }, { name: 'RIVER', potSize: 35, rpValue: 1.2 } ],
    defaultStreetFreqs: {
      flop: { ip_check: 40, ip_bet_small: 45, ip_bet_large: 15, oop_call: 55, oop_fold: 30, oop_raise: 15 },
      turn: { ip_check: 30, ip_bet_small: 40, ip_bet_large: 30, oop_call: 50, oop_fold: 38, oop_raise: 12 },
      river: { ip_check: 25, ip_bet_small: 15, ip_bet_large: 60, oop_call: 60, oop_fold: 32, oop_raise: 8 },
    },
    quiz: { question: 'Por que o Mid pode especular contra o CL?', options: [ { id: 'A', text: 'O custo de entrada é baixo e o ganho em Perspectiva é explosivo.', isCorrect: true }, { id: 'B', text: 'Porque o CL sempre folda contra o Mid.', isCorrect: false }, { id: 'C', text: 'Porque pot odds justificam qualquer call.', isCorrect: false }, { id: 'D', text: 'Porque o Mid tem RP baixo.', isCorrect: false } ], explanation: 'A Especulação Assimétrica funciona porque o investimento é controlado (flat, não 3bet), o custo de errar é absorvível, e o ganho em Perspectiva de acertar é desproporcional: vira CL, mitiga o adversário principal, ganha leverage.' }
  },
  {
    id: 'nodelock-b20',
    name: 'Nodelock B20 (Ancoragem)',
    category: 'clinical',
    stacks: [ 38, 53, 9.4, 52.4, 22.2, 7, 44.3, 24.3, 13.4 ],
    prizes: FT_PRIZES,
    ipRp: 21.4, oopRp: 12.9,
    ipPos: 'BTN', oopPos: 'BB',
    ipMorph: 'Valor Estrito', oopMorph: 'Flat Call Massivo',
    verdict: 'Iniciativa Quebrada',
    narrativeTitle: 'A Algema do ICM',
    narrativeSubtitle: 'IP forçado a B20',
    icon: 'fa-anchor', color: 'blue',
    theory: `Quando o ΔRP algema o IP a usar apenas B20 (20% do pote), a iniciativa pós-flop é destruída. O IP não pode escalonar para barrel grande no turn/river — o BB sabe disso e expande a defesa massivamente. O BB defende hiper-amplo porque sabe que não há ameaça de escalonamento: o sizing fixo do IP remove incerteza, e o BB pode flotar com ranges que seriam indefensáveis contra sizing variável. A Downward Drift atinge seu extremo operacional.`,
    exploit: [ 'Sticky BB: defenda hiper-amplo contra B20.', 'IP perde leverage — check-backs sobem drasticamente.' ],
    sprData: [ { name: 'PRE', potSize: 5.63, rpValue: 12.9 }, { name: 'FLOP', potSize: 11.2, rpValue: 8.5 }, { name: 'TURN', potSize: 22.4, rpValue: 4.2 }, { name: 'RIVER', potSize: 44.8, rpValue: 1.1 } ],
    defaultStreetFreqs: {
      flop: { ip_check: 42, ip_bet_small: 58, ip_bet_large: 0, oop_call: 64, oop_fold: 25, oop_raise: 11 },
      turn: { ip_check: 85, ip_bet_small: 15, ip_bet_large: 0, oop_call: 70, oop_fold: 20, oop_raise: 10 },
      river: { ip_check: 90, ip_bet_small: 10, ip_bet_large: 0, oop_call: 80, oop_fold: 15, oop_raise: 5 },
    },
    quiz: { question: 'Por que o BB expande tanto a defesa contra B20?', options: [ { id: 'A', text: 'Sem ameaça de escalonamento — o IP não pode barrel grande depois.', isCorrect: true }, { id: 'B', text: 'Porque B20 é sempre um blefe.', isCorrect: false }, { id: 'C', text: 'Porque o BB tem posição.', isCorrect: false }, { id: 'D', text: 'Porque o pot é muito pequeno para foldar.', isCorrect: false } ], explanation: 'O sizing fixo de B20 remove a incerteza do BB: ele sabe que não enfrentará barrel de pot no turn. Sem ameaça de escalonamento, o custo de flotar é controlado — ranges que seriam indefensáveis contra sizing variável tornam-se calls lucrativos.' }
  },
  {
    id: 'sniper',
    name: 'Franco-Atirador',
    category: 'toyGame',
    stacks: [ 50, 12, 8, 9, 40, 30, 20, 15, 10 ],
    prizes: FT_PRIZES,
    ipRp: 12, oopRp: 45,
    ipPos: 'SB (CL)', oopPos: 'BB',
    ipMorph: 'Modo Predador', oopMorph: 'Zona de Paralisia',
    verdict: 'Paralisia Extrema',
    narrativeTitle: 'Licença para Matar',
    narrativeSubtitle: 'SB vs BB Death Zone',
    icon: 'fa-crosshairs', color: 'emerald',
    theory: `O SB (CL, 50bb, RP 12%) enfrenta o BB (12bb, RP 45%). Com RP de 45%, o BB precisa de equity absurda para justificar qualquer call — está na Death Zone. O CL pode shover ranges extremamente amplos (potencialmente any two cards) porque a Fold Equity é massiva: o BB colapsa em paralisia estrutural. Mesmo quando o BB acerta o call, o CL sobrevive confortavelmente. A assimetria é tão brutal que o campo gravitacional do ICM paralisa o defensor.`,
    exploit: [ 'Shove ranges extremamente amplos — o BB é paralisado.', 'O custo de estar errado para o CL é mínimo (RP 12%).' ],
    sprData: [ { name: 'PRE', potSize: 1.5, rpValue: 45 }, { name: 'FLOP', potSize: 4, rpValue: 30 }, { name: 'TURN', potSize: 8, rpValue: 15 }, { name: 'RIVER', potSize: 12, rpValue: 9 } ],
    defaultStreetFreqs: {
      flop: { ip_check: 10, ip_bet_small: 30, ip_bet_large: 60, oop_call: 45, oop_fold: 45, oop_raise: 10 },
      turn: { ip_check: 5, ip_bet_small: 20, ip_bet_large: 75, oop_call: 55, oop_fold: 38, oop_raise: 7 },
      river: { ip_check: 5, ip_bet_small: 5, ip_bet_large: 90, oop_call: 65, oop_fold: 28, oop_raise: 7 },
    },
    quiz: { question: 'Por que o CL pode shover quase 100% dos ranges contra o BB?', options: [ { id: 'A', text: 'RP de 45% paralisa o BB — ele precisa de equity absurda para call.', isCorrect: true }, { id: 'B', text: 'Porque o CL tem sempre mãos melhores.', isCorrect: false }, { id: 'C', text: 'Porque 12bb é pouco demais para jogar.', isCorrect: false }, { id: 'D', text: 'Porque o SB tem obrigação de completar.', isCorrect: false } ], explanation: 'Com RP de 45%, o BB está na Death Zone: cada call arrisca a eliminação com custo catastrófico em $EV. A Fold Equity do CL é massiva — o BB é forçado a foldar ranges que seriam calls obrigatórios em ChipEV.' }
  },
  {
    id: 'bully',
    name: 'Bully do Botão',
    category: 'toyGame',
    stacks: [ 80, 20, 18, 15, 12, 10, 8, 5, 4 ],
    prizes: FT_PRIZES,
    ipRp: 5, oopRp: 42,
    ipPos: 'BTN (CL)', oopPos: 'Blinds',
    ipMorph: 'Modo Predador', oopMorph: 'Zona de Paralisia',
    verdict: 'Agressão Impune',
    narrativeTitle: 'Agressão Impune',
    narrativeSubtitle: 'Bolha do ITM',
    icon: 'fa-skull-crossbones', color: 'rose',
    theory: `Na bolha do ITM, o BTN (CL, 80bb, RP 5%) joga quase ChipEV enquanto os Blinds (RP 42%) carregam pressão extrema. A assimetria é a mais brutal do framework: o CL perde pouco quando errado e ganha muito quando certo, enquanto os Blinds perdem tudo quando erram e ganham pouco quando acertam. A agressão do CL é impune — cada fold dos Blinds é lucro garantido, e cada call deles é uma aposta de sobrevivência contra odds esmagadoras.`,
    exploit: [ 'Agressão impune: o custo da perda é mínimo (RP 5%).', 'Cada fold dos Blinds é lucro estrutural garantido.' ],
    sprData: [ { name: 'PRE', potSize: 1.5, rpValue: 42 }, { name: 'FLOP', potSize: 5, rpValue: 31.5 }, { name: 'TURN', potSize: 15, rpValue: 9.5 }, { name: 'RIVER', potSize: 20, rpValue: 4.2 } ],
    defaultStreetFreqs: {
      flop: { ip_check: 15, ip_bet_small: 30, ip_bet_large: 55, oop_call: 45, oop_fold: 47, oop_raise: 8 },
      turn: { ip_check: 10, ip_bet_small: 20, ip_bet_large: 70, oop_call: 55, oop_fold: 38, oop_raise: 7 },
      river: { ip_check: 10, ip_bet_small: 5, ip_bet_large: 85, oop_call: 65, oop_fold: 28, oop_raise: 7 },
    },
    quiz: { question: 'Por que a agressão do CL na bolha é impune?', options: [ { id: 'A', text: 'RP 5% vs 42% — o CL arrisca quase nada, os Blinds arriscam tudo.', isCorrect: true }, { id: 'B', text: 'Porque os Blinds são obrigados a foldar por regra.', isCorrect: false }, { id: 'C', text: 'Porque o CL sempre ganha os showdowns.', isCorrect: false }, { id: 'D', text: 'Porque a bolha não afeta stacks grandes.', isCorrect: false } ], explanation: 'Com RP de 5%, o CL opera quase em ChipEV puro. Os Blinds (RP 42%) pagam custo catastrófico por cada erro. A assimetria de dor cria uma situação onde a agressão é matematicamente impune para o agressor.' }
  }
];
