# utils/ram_optimizer.py
# Nexus SOTA v7.0 GOLD - RAM/VRAM Optimizer
# Manages system memory: WSL limits, Ollama keepalive, process audit
# ASCII-pure. Zero-Any. Typed.
from __future__ import annotations

import gc
import logging
import platform
from pathlib import Path
from typing import TypedDict

try:
    import psutil

    _PSUTIL_OK = True
except ImportError:
    _PSUTIL_OK = False

logger = logging.getLogger(__name__)

USER_HOME = Path.home()
WSL_CONFIG_PATH = USER_HOME / ".wslconfig"
OLLAMA_API_BASE = "http://127.0.0.1:11434"


class ProcessInfo(TypedDict):
    name: str
    pid: int
    ram_mb: float
    cpu_pct: float


class RamReport(TypedDict):
    total_gb: float
    used_gb: float
    free_gb: float
    pct_used: float
    top_processes: list[ProcessInfo]
    wsl_config: dict[str, str]
    ollama_running: bool
    recommendations: list[str]


def get_ram_report(top_n: int = 10) -> RamReport:
    """Generate a complete RAM usage snapshot with recommendations."""
    recommendations: list[str] = []

    if _PSUTIL_OK:
        mem = psutil.virtual_memory()
        total_gb = round(mem.total / 1024**3, 2)
        used_gb = round(mem.used / 1024**3, 2)
        free_gb = round(mem.available / 1024**3, 2)
        pct_used = round(mem.percent, 1)

        procs: list[ProcessInfo] = []
        for proc in psutil.process_iter(["name", "pid", "memory_info", "cpu_percent"]):
            try:
                mi = proc.info["memory_info"]
                if mi is None:
                    continue
                procs.append(
                    {
                        "name": proc.info["name"] or "unknown",
                        "pid": proc.info["pid"] or 0,
                        "ram_mb": round(mi.rss / 1024**2, 1),
                        "cpu_pct": round(proc.info.get("cpu_percent") or 0.0, 1),
                    }
                )
            except (psutil.NoSuchProcess, psutil.AccessDenied):
                continue
        procs.sort(key=lambda p: p["ram_mb"], reverse=True)
        top_processes = procs[:top_n]

        if pct_used > 80:
            recommendations.append("RAM > 80%% used. Consider closing heavy apps (vmmem/WSL, Chrome)")
    else:
        total_gb = used_gb = free_gb = pct_used = 0.0
        top_processes = []
        recommendations.append("psutil not installed - install with: uv add psutil")

    wsl_cfg = _read_wslconfig()
    ollama_ok = _check_ollama_running()

    if ollama_ok:
        recommendations.append("Ollama is running. If idle, run optimize_ollama_keepalive() to free RAM")
    if "memory" not in wsl_cfg:
        recommendations.append("WSL memory not limited. Run apply_wsl_memory_limit(6) to cap at 6 GB")

    return {
        "total_gb": total_gb,
        "used_gb": used_gb,
        "free_gb": free_gb,
        "pct_used": pct_used,
        "top_processes": top_processes,
        "wsl_config": wsl_cfg,
        "ollama_running": ollama_ok,
        "recommendations": recommendations,
    }


def apply_wsl_memory_limit(memory_gb: int = 6, processors: int = 4, swap_gb: int = 2) -> bool:
    """Write or update C:\\Users\\<user>\\.wslconfig to cap WSL memory."""
    if platform.system() != "Windows":
        logger.info("[RAM_OPT] .wslconfig only applies on Windows host - skipping")
        return False
    content = (
        "[wsl2]\n"
        f"memory={memory_gb}GB\n"
        f"processors={processors}\n"
        f"swap={swap_gb}GB\n"
        "guiApplications=true\n"
        "# Auto-generated by Nexus RAM Optimizer SOTA v7.0\n"
    )
    try:
        WSL_CONFIG_PATH.write_text(content, encoding="utf-8")
        logger.info("[RAM_OPT] .wslconfig written: memory=%dGB, processors=%d", memory_gb, processors)
        return True
    except Exception as exc:
        logger.error("[RAM_OPT] Failed to write .wslconfig: %s", exc)
        return False


def optimize_ollama_keepalive(keepalive: int = 0) -> bool:
    """Set Ollama OLLAMA_KEEP_ALIVE=0 to unload model from RAM when idle."""
    try:
        import httpx as _httpx

        # Ollama exposes /api/ps to list loaded models
        resp = _httpx.get(f"{OLLAMA_API_BASE}/api/ps", timeout=5.0)
        models = resp.json().get("models", [])
        if not models:
            logger.info("[RAM_OPT] Ollama: no models currently loaded")
            return True
        # For each loaded model, set keepalive=0 to force unload
        for model_info in models:
            model_name = model_info.get("name", "")
            if not model_name:
                continue
            payload = {"model": model_name, "keep_alive": keepalive}
            unload_resp = _httpx.post(
                f"{OLLAMA_API_BASE}/api/generate",
                json=payload,
                timeout=10.0,
            )
            logger.info("[RAM_OPT] Ollama model %s keepalive=%d -> %d", model_name, keepalive, unload_resp.status_code)
        return True
    except Exception as exc:
        logger.warning("[RAM_OPT] Ollama keepalive optimization failed: %s", exc)
        return False


def apply_gc_pressure() -> int:
    """Force Python garbage collection. Returns number of objects collected."""
    gc.enable()
    n0 = gc.collect(0)
    n1 = gc.collect(1)
    n2 = gc.collect(2)
    total = n0 + n1 + n2
    logger.info("[RAM_OPT] GC: collected %d objects (gen0=%d gen1=%d gen2=%d)", total, n0, n1, n2)
    return total


def format_ram_report(report: RamReport) -> str:
    """Format a RamReport as a rich terminal string."""
    lines: list[str] = [
        "=== RAM AUDIT REPORT ===",
        f"Total: {report['total_gb']} GB  |  Used: {report['used_gb']} GB  |  Free: {report['free_gb']} GB  |  {report['pct_used']}%%",
        f"Ollama: {'RUNNING' if report['ollama_running'] else 'stopped'}  |  WSL config: {report['wsl_config']}",
        "",
        "Top Processes by RAM:",
    ]
    for p in report["top_processes"]:
        lines.append(f"  {p['ram_mb']:>8.1f} MB  {p['name']} (PID {p['pid']})")
    if report["recommendations"]:
        lines.append("")
        lines.append("Recommendations:")
        for rec in report["recommendations"]:
            lines.append(f"  >> {rec}")
    return "\n".join(lines)


# ------------------------------------------------------------------
# Private helpers
# ------------------------------------------------------------------


def _read_wslconfig() -> dict[str, str]:
    if not WSL_CONFIG_PATH.exists():
        return {}
    result: dict[str, str] = {}
    try:
        for line in WSL_CONFIG_PATH.read_text(encoding="utf-8").splitlines():
            line = line.strip()
            if "=" in line and not line.startswith("#") and not line.startswith("["):
                k, _, v = line.partition("=")
                result[k.strip()] = v.strip()
    except Exception:
        pass
    return result


def _check_ollama_running() -> bool:
    try:
        import httpx

        r = httpx.get(f"{OLLAMA_API_BASE}/api/ps", timeout=2.0)
        return r.status_code == 200
    except Exception:
        return False
